
on:
  push:
    branches:
    - ci
    tags:
    - 'v*'

name: Build

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: scripts/ci
    - run: cp -r /bin/manager ./package/
    - if: ${{ startsWith(github.ref, 'refs/heads/') }}
      uses: docker/build-push-action@v2
      with:
        context: ./package
        file: ./package/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/rancher-sandbox/opni-opensearch-operator:latest