name: Test
on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17'
    - run: hack/setup-envtest.sh
    - run: go test ./... -race -v --ginkgo.label-filter "(unit || controller)"